line-length = 100
target-version = "py312"

extend-exclude = ["src/untappd_parser_bundle.py"]

[lint.isort]
split-on-trailing-comma = false

[format]
quote-style = "preserve"
skip-magic-trailing-comma = false
